export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ACTIVATITON_SUCCESS = "ACTIVATITON_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";


export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";

//Alerts
export const SET_ALERT = "SET_ALERT";
export cont REMOVE_ALERT = "REMOVE_ALERT";